services:
  arweave-api:
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    container_name: arweave-api
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.env:/app/.env
