services:
  arweave-api:
    image: arweave-api:$TAG
    container_name: arweave-api
    ports:
      - '3000:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.env:/app/.env
