name: Deploy Docker Container

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/docker-build.yml@docker-build-v2.2.0
    with:
      dockerfile: 'Dockerfile'
      image-name: 'iexechub/arweave-api'
      image-tag: ${{ github.sha }}
      hadolint: false
      security-scan: false
      push: true
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_PAT }}
  deploy:
    runs-on:
      group: Azure_runners

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if SSH key exists
        run: |
          if [ ! -f ~/.ssh/ghrunnerci ]; then
            echo "SSH key not found at ~/.ssh/ghrunnerci"
            exit 1
          fi

      - name: Set permissions on existing SSH key
        run: chmod 600 ~/.ssh/ghrunnerci

      - name: Add remote host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan azubdocxp-team-product.public.az2.internal >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Check if docker-compose.yml exists
        run: |
          if [ ! -f docker-compose.yml ]; then
            echo "docker-compose.yml not found in the repository"
            exit 1
          fi

      - name: Copy docker-compose.yml to remote server
        uses: appleboy/scp-action@v1
        with:
          host: azubdocxp-team-product.public.az2.internal
          username: ghrunnerci
          key_path: ~/.ssh/ghrunnerci
          port: 22
          source: "./docker-compose.yml"
          target: "/opt/arweave-api"
          timeout: 30s
          debug: true
          command_timeout: 10m

      - name: Run Docker Compose on remote server
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i ~/.ssh/ghrunnerci \
              ghrunnerci@azubdocxp-team-product.public.az2.internal << 'EOF'
            cd /opt/arweave-api
            docker compose pull
            docker compose up -d
          EOF
