name: Deploy Docker Container

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
#   build:
#     uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/docker-build.yml@docker-build-v2.2.0
#     with:
#       dockerfile: 'Dockerfile'
#       # With tag
#       image-name: 'arweave-api'
#       image-tag: ${{ github.sha }}
#       hadolint: false
#       security-scan: false
#       push: true
#       registry: 'docker-regis.iex.ec/arweave-api'
#     secrets:
#       username: ${{ secrets.NEXUS_USERNAME }}
#       password: ${{ secrets.NEXUS_PASSWORD }}
  deploy:
    runs-on:
      group: Azure_runners

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ~/.ssh folder
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add remote host to known_hosts
        run: |
          ssh-keyscan azubdocxp-team-product.public.az2.internal >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Create remote deploy folder if missing
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i ~/.ssh/id_rsa \
              ghrunnerci@azubdocxp-team-product.public.az2.internal "mkdir -p ~/deploy"

      - name: Copy docker-compose.yml to remote server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: azubdocxp-team-product.public.az2.internal
          username: ghrunnerci
          key_path: ~/.ssh/id_rsa
          port: 22
          source: "docker-compose.yml"
          target: "~/deploy/"
          timeout: 30s
          command_timeout: 10m

      - name: Run Docker Compose on remote server
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i ~/.ssh/id_rsa \
              ghrunnerci@azubdocxp-team-product.public.az2.internal << 'EOF'
            cd ~/deploy
            docker compose pull
            docker compose up -d
          EOF
