name: Deploy Docker Container


on: [push, workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on:
      group: Azure_runners
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: 'IDENTITY'
          tenant-id: ${{ secrets.AZURE_MCA_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Get SSH key from Azure Key Vault
        id: get-secret
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            set -euo pipefail
            SECRET=$(az keyvault secret show \
              --vault-name kv-iexec-github-actions \
              --name StorageAccountKey \
              --query value -o tsv)
            echo "::add-mask::$SECRET"
            echo "secret_value=$SECRET" >> $GITHUB_OUTPUT

      - name: Deploy
        uses: kitconcept/docker-stack-deploy@v1.2.0
        with:
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_private_key: ${{ steps.get-secret.outputs.secret_value }}
          stack_file: stacks/api.yml
          stack_name: arweave-api
