name: Deploy Docker Container

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on:
      group: Azure_runners
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          tenant-id: ${{ secrets.AZURE_MCA_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Get SSH key from Azure Key Vault and set env var
        id: fetch-secret
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            set -euo pipefail

            RAW_KEY=$(az keyvault secret show \
              --vault-name kv-iexec-github-actions \
              --name githubactionsrunners-sshkey \
              --query value -o tsv)

            echo "::add-mask::$RAW_KEY"

            echo "SSH_KEY<<GITHUB_ENV_DELIMITER_12345" >> $GITHUB_ENV
            echo "$RAW_KEY"                     >> $GITHUB_ENV
            echo "GITHUB_ENV_DELIMITER_12345"   >> $GITHUB_ENV

      - name: Deploy Docker Stack
        uses: kitconcept/docker-stack-deploy@v1.2.0
        with:
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_private_key: ${{ env.SSH_KEY }}
          stack_file: stacks/api.yml
          stack_name: arweave-api