name: Deploy Docker Container

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
#   build:
#     uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/docker-build.yml@docker-build-v2.2.0
#     with:
#       dockerfile: 'Dockerfile'
#       # With tag
#       image-name: 'arweave-api'
#       image-tag: ${{ github.sha }}
#       hadolint: false
#       security-scan: false
#       push: true
#       registry: 'docker-regis.iex.ec/arweave-api'
#     secrets:
#       username: ${{ secrets.NEXUS_USERNAME }}
#       password: ${{ secrets.NEXUS_PASSWORD }}
  deploy:
    runs-on:
      group: Azure_runners
    needs: build
    steps:

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ensure known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Copy docker-compose.yml to remote server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "~/deploy/" # Check the path

      - name: Run Docker Compose on remote server
        run: |
          ssh -o StrictHostKeyChecking=no "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" << 'EOF'
            cd ~/deploy  # Check the path
            docker compose pull
            docker compose up -d
          EOF
