name: Test Build Docker Container

on: [pull_request]

jobs:
  test-build:
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/docker-build.yml@docker-build-v2.2.0
    with:
      dockerfile: 'Dockerfile'
      image-name: 'arweave-api'
      image-tag: ${{ github.sha }}
